### ISSUE TITLE
add known answer tests

### ISSUE THREAD

**Issue by oreparaz** [oreparaz/p256#2]
Coverage today is pretty minimal. We'd benefit from adding more known answer tests. Can steal the test vectors from other libraries or wycheproof.

The testing framework is already in place so this shouldn't take too long.

**Comment by 0adb** [comment]
Would like to work on this; will take answer tests from https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/digital-signatures.

**Comment by oreparaz** [comment]
Awesome, thank you Arthur for your work on this. Closing this as your PR was merged 👏🏻
